# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=50)),
                ('PoName', models.CharField(max_length=200)),
                ('ShortName', models.CharField(max_length=20)),
                ('EnShortName', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
                ('Tel', models.CharField(max_length=20)),
                ('Fax', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
                ('Web', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
    ]
