# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['Code']},
        ),
        migrations.AlterField(
            model_name='company',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='EnShortName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='Fax',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='PoName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='Type',
            field=models.CharField(choices=[('1', '\u5b50\u516c\u53f8'), ('2', '\u5206\u5224\u516c\u53f8')], max_length=1),
        ),
        migrations.AlterField(
            model_name='company',
            name='Web',
            field=models.URLField(blank=True),
        ),
    ]
